// Generated by CoffeeScript 1.7.1
window.euler = window.euler || {};

euler.evenFibSum = function(limit) {
  var a, b, sum, x;
  sum = 0;
  a = 1;
  b = 2;
  while (b < limit) {
    if (b % 2 === 0) {
      sum += b;
    }
    x = a;
    a = b;
    b += x;
  }
  return sum;
};
