// Generated by CoffeeScript 1.7.1
if (!window.euler) {
  window.euler = {};
}

euler.primeFactor = function(n) {
  var i;
  i = 2;
  while (i < n) {
    if (n % i === 0) {
      n /= i;
    }
    i++;
  }
  return i;
};
